# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URWEB = urweb
UWCC = $(shell $(shell $(URWEB) -print-ccompiler) -print-prog-name=gcc)
UWFLAGS = 
UWINCLUDE = $(shell $(URWEB) -print-cinclude)
UWINCLUDEDIR = $(shell $(URWEB) -print-cinclude)/..
UWVER = $(shell $(URWEB) -version)
.PHONY: ./all
./all: ./Makefile ./test/Captcha1.db ./test/Captcha1.exe ./test/Captcha1.sql
./test/Captcha1.db: ./Makefile ./test/Captcha1.exe ./test/Captcha1.sql
	dropdb --if-exists Captcha1
	createdb Captcha1
	psql -f ./test/Captcha1.sql Captcha1
	touch ./test/Captcha1.db
./.cake3/tmp___test_Captcha1_in_2: ./Makefile ./lib.urp ./test/Captcha1.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo $$\/char  ;\
	echo $$\/string  ;\
	echo \.\.\/test\/Captcha1  ;\
	) > ./.cake3/tmp___test_Captcha1_in_2
./.cake3/tmp___test_Captcha1_in_1: ./Makefile ./lib.urp ./test/Captcha1.ur
	( \
	echo database\ dbname\=Captcha1  ;\
	echo sql\ \.\.\/test\/Captcha1\.sql  ;\
	echo library\ \.\.\/  ;\
	echo safeGet\ Captcha1\/captcha\_show  ;\
	echo safeGet\ Captcha1\/main  ;\
	echo allow\ mime\ image\/gif  ;\
	) > ./.cake3/tmp___test_Captcha1_in_1
./.cake3/tmp___lib_in_2: ./Captcha.ur ./Captcha_ffi.h ./Captcha_ffi.o ./Makefile ./lib/captcha/libcaptcha.a
	( \
	echo   ;\
	echo \.\/Captcha  ;\
	) > ./.cake3/tmp___lib_in_2
./.cake3/tmp___lib_in_1: ./Captcha.ur ./Captcha_ffi.h ./Captcha_ffi.o ./Makefile ./lib/captcha/libcaptcha.a
	( \
	echo ffi\ \.\/Captcha\_ffi  ;\
	echo include\ \.\/Captcha\_ffi\.h  ;\
	echo link\ \.\/Captcha\_ffi\.o  ;\
	echo link\ \.\/lib\/captcha\/libcaptcha\.a  ;\
	) > ./.cake3/tmp___lib_in_1
./lib/captcha/libcaptcha.a: ./Makefile ./lib/captcha/Makefile
	make -C ./lib/captcha
	touch -c ./lib/captcha/libcaptcha.a
./lib/captcha/Makefile: ./Makefile
	git -C . submodule update --init
	git -C ./lib/captcha checkout -f
	touch -c ./lib/captcha/Makefile
.PHONY: ./test
./test: ./Makefile ./test/Captcha1.db ./test/Captcha1.exe ./test/Captcha1.sql
.PHONY: ./lib
./lib: ./Makefile ./lib.urp
.INTERMEDIATE: ./.fix-multy1
./.fix-multy1: ./Makefile ./test/Captcha1.urp $(call GUARD,URWEB) $(call GUARD,UWFLAGS) $(call GUARD,UWINCLUDEDIR) $(call GUARD,UWVER)
	C_INCLUDE_PATH=$(UWINCLUDEDIR) $(URWEB) -dbms postgres $(UWFLAGS) ./test/Captcha1
./Captcha_ffi.o: ./Captcha_ffi.c ./Makefile $(call GUARD,UWCC) $(call GUARD,UWCFLAGS) $(call GUARD,UWINCLUDE) $(call GUARD,UWINCLUDEDIR)
	$(UWCC) -c -I$(UWINCLUDEDIR) -I$(UWINCLUDE) $(UWCFLAGS)  -o ./Captcha_ffi.o ./Captcha_ffi.c
./lib.urp: ./.cake3/tmp___lib_in_1 ./.cake3/tmp___lib_in_2 ./Makefile
	cat ./.cake3/tmp___lib_in_1 > ./lib.urp
	cat ./.cake3/tmp___lib_in_2 >> ./lib.urp
./test/Captcha1.exe: ./.fix-multy1
./test/Captcha1.sql: ./.fix-multy1
./test/Captcha1.urp: ./.cake3/tmp___test_Captcha1_in_1 ./.cake3/tmp___test_Captcha1_in_2 ./Makefile
	cat ./.cake3/tmp___test_Captcha1_in_1 > ./test/Captcha1.urp
	cat ./.cake3/tmp___test_Captcha1_in_2 >> ./test/Captcha1.urp
$(call GUARD,URWEB):
	rm -f .cake3/GUARD_URWEB_*
	touch $@
$(call GUARD,UWCC):
	rm -f .cake3/GUARD_UWCC_*
	touch $@
$(call GUARD,UWCFLAGS):
	rm -f .cake3/GUARD_UWCFLAGS_*
	touch $@
$(call GUARD,UWFLAGS):
	rm -f .cake3/GUARD_UWFLAGS_*
	touch $@
$(call GUARD,UWINCLUDE):
	rm -f .cake3/GUARD_UWINCLUDE_*
	touch $@
$(call GUARD,UWINCLUDEDIR):
	rm -f .cake3/GUARD_UWINCLUDEDIR_*
	touch $@
$(call GUARD,UWVER):
	rm -f .cake3/GUARD_UWVER_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: ./all
./all: ./.fix-multy1
.PHONY: ./test/Captcha1.db
./test/Captcha1.db: ./.fix-multy1
.PHONY: ./.cake3/tmp___test_Captcha1_in_2
./.cake3/tmp___test_Captcha1_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test_Captcha1_in_1
./.cake3/tmp___test_Captcha1_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___lib_in_2
./.cake3/tmp___lib_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___lib_in_1
./.cake3/tmp___lib_in_1: ./.fix-multy1
.PHONY: ./lib/captcha/libcaptcha.a
./lib/captcha/libcaptcha.a: ./.fix-multy1
.PHONY: ./lib/captcha/Makefile
./lib/captcha/Makefile: ./.fix-multy1
.PHONY: ./test
./test: ./.fix-multy1
.PHONY: ./lib
./lib: ./.fix-multy1
.INTERMEDIATE: ./.fix-multy1
./.fix-multy1:
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)
.PHONY: ./Captcha_ffi.o
./Captcha_ffi.o: ./.fix-multy1
.PHONY: ./lib.urp
./lib.urp: ./.fix-multy1
.PHONY: ./test/Captcha1.exe
./test/Captcha1.exe: ./.fix-multy1
.PHONY: ./test/Captcha1.sql
./test/Captcha1.sql: ./.fix-multy1
.PHONY: ./test/Captcha1.urp
./test/Captcha1.urp: ./.fix-multy1

endif
.PHONY: ./clean
./clean:
	-rm ./.cake3/tmp___lib_in_1 ./.cake3/tmp___lib_in_2 ./.cake3/tmp___test_Captcha1_in_1 ./.cake3/tmp___test_Captcha1_in_2 ./Captcha_ffi.o ./lib.urp ./lib/captcha/Makefile ./lib/captcha/libcaptcha.a ./test/Captcha1.db ./test/Captcha1.exe ./test/Captcha1.sql ./test/Captcha1.urp
	-rm -rf .cake3

endif
